app/models.py
from . import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String)
    username = db.Column(db.String)
    email = db.Column(db.String)
    pass_secure = db.Column(db.String(255))
    
    pitch = db.relationship('Pitch', backref='user', lazy="dynamic")
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)


class Pitch(db.Model):
    """docstring for Pitch class that defines the piches object. Getting pitches and single pitch"""
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    content = db.Column(db.String(1000))
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls):
        pitches = Pitch.query.all()

        return pitches

    @classmethod
    def get_single_pitch(cls, id):
        single_pitch = Pitch.query.filter_by(id=id).first()

        return single_pitch

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required


class PitchForm(FlaskForm):
    description = TextAreaField('Your Post', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY'] = 'rfuywelfhujufylbhsdjlhfrsrbsdhsdb'

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
import datetime
from .forms import PitchForm

from . import main
from ..models import User, Pitch

# Views
@main.route('/')
def index():
    title = 'Pitches App'
    pitches = Pitch.get_pitches()

    return render_template('index.html', title=title, pitches=pitches)


@main.route('/pitch/<int:id>', methods=['GET', 'POST'])
def pitch(id):
    pitch = Pitch.get_single_pitch(id)
    posted_date = pitch.posted.strftime('%b %d, %Y')

    if request.args.get("like"):
        pitch.likes = pitch.likes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))
    elif request.args.get("dislikes"):
        pitch.dislikes = pitch.dislikes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))
    return render_template('pitch.html', pitch=pitch, date=posted_date)


@main.route('/pitch/new', methods=['GET', 'POST'])
@login_required
def new_pitches():
    pitch_form = PitchForm()
    if pitch_form.validate_on_submit():
        # title = request.form['title']
        # Comment = request.form['comment']

        # updating pitch instance
        if pitch_form.validate_on_submit():
            new_pitch = Pitch(content=pitch_form.description.data, user=current_user, likes=0, dislikes=0)
            # save pitch
            new_pitch.save_pitch()
            return redirect(url_for('main.index'))

    title = 'New Pitch'
    return render_template('new_pitches.html', title=title, pitch_form=pitch_form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block styles%}
  {{super()}}

  <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans" rel="stylesheet">
{%endblock%}

{% block navbar %}
  {%include 'navbar.html'%}
{%endblock%}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1 class="text-center">Pitching in 60 seconds</h1>
</div>

{%for pitch in pitches%}
<style>
	* {
		background-attachment: fixed;
		background-image: url('https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fmax%2F3308%2F1*VgdsW_Z6q-1xnYnaC4Uckw.png&imgrefurl=https%3A%2F%2Fmedium.com%2F%40diegzis%2Fhow-to-pitch-your-creative-idea-b13e0e0ff0a7&docid=6CWtECW3XFs92M&tbnid=BPTxReqJuainkM%3A&vet=10ahUKEwihkZGStYLnAhWrUBUIHY6cCSUQMwhNKAEwAQ..i&w=1654&h=714&bih=588&biw=1296&q=pitching%20an%20idea&ved=0ahUKEwihkZGStYLnAhWrUBUIHY6cCSUQMwhNKAEwAQ&iact=mrc&uact=8');
		background-repeat: no-repeat;
		background-size: cover;
		color: antiquewhite;
	}

	#wow {
		padding: 5%;
	}

	#me {
		margin-left: 50%;
	}
</style>
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card" id="wow">
	<div class="well well-lg">
		<h4>Written by: {{pitch.user.username}}</h4>
		<p>{{pitch.content}}</p>
		<p><a href="/pitch/{{pitch.id}}" class="btn btn-primary pull-right">Read</a>
		</p>
	</div>
</div>
{%endfor%}
<div class="container" style="padding-bottom: 20px;">
	<a href="{{url_for('main.new_pitches')}}" class="btn btn-success" id="me">Create pitch</a>
</div>

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Pitches </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                
        </div>

    </div>
</div>

app/templates/new_pitches.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<h3>{{title}}</h3>
{{wtf.quick_form(pitch_form)}}

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
    integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{%endblock%}
<!-- Content block -->
{%block content%}
<style>
    * {
        background-image: url('https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fmax%2F3308%2F1*VgdsW_Z6q-1xnYnaC4Uckw.png&imgrefurl=https%3A%2F%2Fmedium.com%2F%40diegzis%2Fhow-to-pitch-your-creative-idea-b13e0e0ff0a7&docid=6CWtECW3XFs92M&tbnid=BPTxReqJuainkM%3A&vet=10ahUKEwihkZGStYLnAhWrUBUIHY6cCSUQMwhNKAEwAQ..i&w=1654&h=714&bih=588&biw=1296&q=pitching%20an%20idea&ved=0ahUKEwihkZGStYLnAhWrUBUIHY6cCSUQMwhNKAEwAQ&iact=mrc&uact=8');
        background-repeat: no-repeat;
        color: antiquewhite;
        background-attachment: fixed;
    }
</style>
<div class="container" style="font-family: 'Indie Flower', cursive;">
    <div class="row">
        <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>

        <hr>
        <p>{{pitch.content}}</p>
        <span>
            <br>
            <a href="/pitch/{{pitch.id}}?like=1">
                <i class="far fa-thumbs-up"></i>
            </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">
                <i class="far fa-thumbs-down"></i>
            </a>{{pitch.dislikes}}
        </span>

    </div>
    {%endblock%}